[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
